### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by dntzbgh** [scionoftech/webptools#2]
I get the next error when trying to use the examples you posted. Seems to be a problem with the function `getwebp()` when you pass the parameters.
```
Traceback (most recent call last):
  File "C:/Users/Dan/PycharmProjects/projects/webp_convert.py", line 4, in <module>
    print(str(webp.dwebp(input_image='random_703.webp',output_image='random_703.png',option='0')))
  File "C:\Users\Dan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\webptools\webplib.py", line 29, in dwebp
    cmd = getdwebp() + ' ' + input_image + ' ' + option + ' ' + output_image
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

```

**Comment by DaVinci0072** [comment]
Same here using Python 3.7.4 32-bit.  Problem does not happen on Python 2.7.16 64-bit.

Using webptools-0.0.2
